### ISSUE TITLE
Missing `println` primitive

### ISSUE THREAD

**Issue by skx** [eatonphil/goi#2]
The [blog-post introducing this code](http://notes.eatonphil.com/interpreting-go.html) has a `println` primitive.

The code here does not contain that.

**Comment by eatonphil** [comment]
Thanks! Originally I was using a (syntactically/semantically) invalid return from main to get a result and I forgot to switch over. Closed in https://github.com/eatonphil/goi/commit/5716ad33c3945da04bee571e5bd5bb03e9884353.
